// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  ObjectName = 3,
  String = 4,
  ObjectVal = 5,
  ObjectType = 6,
  Parameter = 7,
  ParName = 8,
  ParVal = 9
