// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "%QOVQPOOOOQO'#Cf'#CfOVQPOOOOQO'#C`'#C`OOQO'#C_'#C_O_QPO'#C^QdQPOOOOQO-E6d-E6dOYQPO,58xOVQPO'#ChQdQPOOOOQO'#Cb'#CbOiQPO'#CaOOQO1G.d1G.dOOQO,59S,59SOOQO-E6f-E6fOtQPO,58{O|QPO1G.gO!XQPO1G.gOOQO1G.g1G.gOOQO'#Cd'#CdO!aQPO'#CcOOQO,59R,59ROOQO7+$R7+$RO!fQPO7+$ROOQO-E6e-E6eOYQPO,58}OOQO<<Gm<<GmPVQPO'#CfOOQO'#Ce'#CeOOQO1G.i1G.i",
  stateData: "!q~O_OS~O`POaRO~ObWO~O`PO~Oc`O]TX`TX~O`POdcO~O`POaROdgO~O`POdgO~ObjO~O`POaROdkO~O",
  goto: "#P]PP^ejz}!Q!V![!_!s!ySUOQR^XVTOQXUSOQXQZWUdahlRmjR]WR[WVfahlVeahlRnjQQOYVQXahlSXUYQa`RhbQb`RibQYUR_Y",
  nodeNames: "⚠ Program Statement ObjectName String ObjectVal ObjectType Parameter ParName ParVal",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "#X~RWYZkpqp!Q![u!_!`!x!c!}u#T#ou#o#p!}#q#r#S~pO`~~uO_~~zSa~pq!W!Q![u!c!}u#T#ou~!ZSpq!W!Q![!g!c!}!g#T#o!g~!lSa~pq!W!Q![!g!c!}!g#T#o!g~!}Ob~~#SOc~~#XOd~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
