// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: ",xOVQPOOOOQO'#Cn'#CnOVQPOOObQQO'#C^ObQQO'#C^QgQPOOOOQO-E6l-E6lOOQO'#C`'#C`OOQO'#C_'#C_OlQPO,58xOOQO'#Ci'#CiOqQPO,58xOVQPO'#CsQgQPOOObQQO1G.dOvQPO'#CjOOQO1G.d1G.dOOQO,59_,59_OOQO-E6q-E6qOOQO'#Cb'#CbO!OQPO'#CaOOQO7+$O7+$OOOQO'#Ck'#CkObQQO'#CkO!^QPO,59UO!cQPO,58{OOQO'#Cl'#ClO!kQPO,59VObQQO,59VO!sQPO1G.pO!{QQO1G.gO#ZQPO1G.gOOQO1G.g1G.gOOQO,59],59]OOQO1G.q1G.qO#cQPO1G.qOOQO-E6o-E6oO#kQPO7+$[OgQPO7+$[OOQO'#Ce'#CeO#sQPO'#CdOOQO'#Cc'#CcObQQO'#CcOOQO,59Z,59ZOOQO7+$R7+$RO#xQQO7+$ROOQO-E6m-E6mOOQO7+$]7+$]P$WQPO'#CqOgQPO<<GvO$]QQO<<GvObQQO,59OOOQO'#Cg'#CgO$kQPO,58}OOQO<<Gm<<GmP$pQQO'#CnO$]QQOAN=bObQQO'#CmO${QPO'#CmO%TQPOAN=bOOQO'#Cf'#CfOOQO1G.j1G.jObQQO1G.iO%YQPOG22|O%_QPO,59XO%dQQO,59XO%rQPO,59XOOQOG22|G22|O%zQPO'#ChOOQO7+$T7+$TOOQOLD(hLD(hObQQO1G.sO&VQQO1G.sO&eQPO,59SO&mQPO7+$_O&uQQO1G.nO'QQPO1G.nOOQO1G.n1G.nO'YQPO'#CrO'bQPO<<GyOOQO,59[,59[OOQO7+$Y7+$YO'jQQO7+$YOOQO-E6n-E6nObQQO,59^OOQO-E6p-E6pOOQO<<Gt<<GtP'uQQO'#CnO'}QPO1G.xObQQO7+$dOOQO<<HO<<HO",
  stateData: "(S~OjOS~OkPOlROrSO~OmVO~OkPO~On^O~Os_O~OsgOtfO~OoiOhTXkTXqTX~OvmO~OkPOqpO~OuqOvrO~OkPOovO~OkPOmVOpzOq|O~OkPOq|O~OuqOv!PO~OkPOo!RO~On!TO~OkPOmVOpzOq!WO~OuqO~OkPOl!ZOmVOpzO~On!`O~OkPOmVOpzO~OkPOqaX~Oq!eO~Oq!hO~On!iO~OkPOmVOpzOqaa~OkPOqaa~Oo!kOk[Xq[X~OkPOmVOpzOqai~OkPOq!oO~OkPOqaq~OkPOmVOq!sO~OkPOq!sO~OkPOl!vO~OkPOqay~OkPOmVOq!xO~OkPOmVO~On!{O~O",
  goto: "&chPPipy!o!x#Q#]#k#w#z#}$Q$T$W$Z$a$g%o%y&P&V&]STOQRa[QXRQ!b!ZR!z!vUWR!Z!vQYSWc^!`!i!{Sjgldwn}!S!X!Y!c!j!m!t!yQ!UzR!^!TQe^Q!l!iR!|!{Ud^!i!{R!f!`Y{n}!X!c!jT![!S!Y^yn}!S!X!Y!c!jV!r!m!t!yexn}!S!X!Y!c!j!m!t!yR!_!TR!VzR!g!`RZSR`ZRh_QkgRslQ!]!SR!a!YQQOlUQ[nu}!S!X!Y!c!j!m!p!t!yS[T]QniQumQ}oQ!SvQ!Y!RQ!c![Q!j!dQ!m!kS!p!l!qR!t!nQoiS!Oo!dR!d![Q!n!kR!u!nQlgRtlQ!q!lR!w!qQ]TRb]",
  nodeNames: "⚠ Program Statement ModelName String Type Template SubStatement Parameter ParName ParVal ObjectName ObjectVal ClassName Class ClassParameters ClassParameter ClassDefinition",
  maxTerm: 38,
  skippedNodes: [0],
  repeatNodeCount: 6,
  tokenData: "&q~R_YZ!Qpq!Vqr![st!axy!fyz!s|}!x!Q![!}!_!`$Q!c!e!}!e!f$V!f!}!}#T#o!}#o#p&g#q#r&l~!VOk~~![Oj~~!aOl~~!fOp~~!kPs~yz!n~!sOt~~!xOv~~!}Ou~Q#SSmQpq#`!Q![!}!c!}!}#T#o!}Q#cSpq#`!Q![#o!c!}#o#T#o#oQ#tSmQpq#`!Q![#o!c!}#o#T#o#o~$VOn~R$[UmQpq#`!Q![!}!c!}!}#T#`!}#`#a$n#a#o!}R$sTmQpq#`!Q![!}!c!}!}#T#U%S#U#o!}R%XUmQpq#`!Q![!}!c!}!}#T#g!}#g#h%k#h#o!}R%pUmQpq#`!Q![!}!c!}!}#T#g!}#g#h&S#h#o!}R&ZSrPmQpq#`!Q![!}!c!}!}#T#o!}~&lOo~~&qOq~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
