// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  ModelName = 3,
  String = 4,
  Type = 5,
  Template = 6,
  SubStatement = 7,
  Parameter = 8,
  ParName = 9,
  ParVal = 10,
  ObjectName = 11,
  ObjectVal = 12,
  ClassName = 13,
  Class = 14,
  ClassParameters = 15,
  ClassParameter = 16,
  ClassDefinition = 17
